#! /bin/bash
cd $(dirname $0) &&
git add --all &&
if git commit --dry-run; then git commit -m 'sy'; fi &&
git fetch &&
( git merge --no-commit --no-ff || ( echo && echo Use '"git merge"' to merge, then edit merged file && echo && false ) ) &&
git push &&
syput &&
ssh i19 "cd $(pwd); if [ -f report/report.pdf ]; then chmod 0644 report/report.pdf; fi"
