T_Head = r"""% !TEX encoding = UTF-8 Unicode
% generated by %program% on %now%
%documentclass%
\pagestyle{empty}
\usepackage[cm]{fullpage}
\usepackage{verbatim}
\usepackage[table]{xcolor}
\usepackage{tikz}               % draw filled circles in \ColorCodedByRegion

\usepackage{graphicx}           % multiple pdfs per page, pdf
\usepackage[export]{adjustbox}  % frame in \includegraphics
\usepackage{grffile}            % to allow .a.pdf in \includegraphics
\usepackage{pdfpages}           % phylogenetic tree
\usepackage{fancyhdr}           % keep page numbers in embedded phylogenetic tree
\usepackage{calc}
\usepackage{hyperref}           % ToC entries as links
\usepackage{tocloft}            % \cftsetindents
\usepackage[toc,page]{appendix} % Appendice
\usepackage{titletoc}           % ToC entries without numbers
\usepackage[T1]{fontenc}        % fonts
\usepackage{times}              % font

%usepackage%
"""

# ----------------------------------------------------------------------

T_Tail = r"""
% ---------------------------------------------------------
\end{document}
"""

# ----------------------------------------------------------------------

T_RemoveSectionNumbering = r"""
% ----------------------------------------------------------------------
% remove section numbering
% ----------------------------------------------------------------------

%% http://www.ehow.com/how_8085363_hide-section-numbers-latex.html
\setcounter{secnumdepth}{-1}

"""

# ----------------------------------------------------------------------

T_ColorCodedBy = r"""
% ----------------------------------------------------------------------
% ColorCodedBy
% ----------------------------------------------------------------------
% \newcommand\cbox[1][black]{\textcolor{#1}{\rule{0.7em}{0.7em}}}
\newcommand\cbox[1][black]{\tikz[baseline=-0.5ex]\draw[black,fill=#1,radius=0.3em] (0,0) circle ;}

\newcommand{\ColorCodedByRegion}{%
  \begin{tabular}{l l l}
    \cbox[NorthAmerica]     & North America            & Dark Blue \\
    \cbox[SouthAmerica]     & South America            & Light Blue \\
    \cbox[Europe]           & Europe                   & Green \\
    \cbox[Africa]           & Africa                   & Orange \\
    \cbox[MiddleEast]       & MiddleEast               & Purple \\
    \cbox[Russia]           & Russia                   & Maroon \\
    \cbox[Asia]             & East and South East Asia & Red \\
    \cbox[AustraliaOceania] & Australia and Oceania    & Pink \\
    \cbox[Unknown]          & unknown                  & Grey \\
  \end{tabular}
}

\newcommand{\ColorCodedByRegionOld}{%
{\color{NorthAmerica}DarkBlue = NorthAmerica} \\
{\color{SouthAmerica}LightBlue = SouthAmerica} \\
{\color{Europe}Green = Europe} \\
{\color{Africa}Orange = Africa} \\
{\color{MiddleEast}Purple = MiddleEast} \\
{\color{Russia}Maroon = Russia} \\
{\color{Asia}Red = E SE Asia} \\
{\color{AustraliaOceania}Pink = Oceania} \\
{\color{Unknown}Grey = unknown}
}

\definecolor{2a1b.2}{HTML}{1B9E77}
\definecolor{2a1b.1}{HTML}{66A61E}
\definecolor{2a1b.2a1}{HTML}{D95F02}
\definecolor{2a1b.2a2}{HTML}{E6AB02}
\definecolor{2a1b.2a2 156S}{HTML}{674d01}
\definecolor{2a1b.2a2 156Q}{HTML}{fede83}
\definecolor{2a1b1a}{HTML}{4037B3}
\definecolor{2a1b1a+192F}{HTML}{9a4ef2}
\definecolor{2a1b.1b}{HTML}{E7298A}

\newcommand{\ColorCodedHThreeSecondSet}{%
  \begin{tabular}{l l}
    \cbox[2a1b.2]     & 2a1b.2 \\
    \cbox[2a1b.1]     & 2a1b.1 \\
    \cbox[2a1b.2a1]      & 2a1b.2a1 \\
    \cbox[2a1b.2a2]      & 2a1b.2a2 \\
    \cbox[2a1b.2a2 156S] & 2a1b.2a2 156S \\
    \cbox[2a1b.2a2 156Q] & 2a1b.2a2 156Q \\
    \cbox[2a1b1a]        & 2a1b1a \\
    \cbox[2a1b1a+192F]   & 2a1b1a+192F \\
    \cbox[2a1b.1b]       & 2a1b.1b \\
  \end{tabular}
}

% \newcommand{\ColorCodedByLineage}{%
% {\color{Yamagata}Red = Yamagata},
% {\color{Victoria}Blue = Victoria}.
% {\color{Victoria}Green = Victoria deletion mutants}.
% }

\newcommand{\ColorCodedByLineageVicDelMut}{%
  \begin{tabular}{l l l}
    \cbox[Yamagata]     & Yamagata               & Red \\
    \cbox[Victoria]     & Victoria               & Blue \\
    \cbox[Victoria2del] & Victoria 2-del mutants & Cyan \\
    \cbox[Victoria3del] & Victoria 3-del mutants & Purple \\
  \end{tabular}
}

\definecolor{V1A.3 126K}       {HTML}{8DA0CB}
\definecolor{V1A.3 133G 129N}  {HTML}{8C6BB1}
\definecolor{V1A.3a}           {HTML}{66C2A5}
\definecolor{V1A.3a1}          {HTML}{33A02C}
\definecolor{V1A.3a2}          {HTML}{CCFF9E}
\definecolor{V1A.3a2 122Q}     {HTML}{A6D854}
\definecolor{V1A.3 133R}       {HTML}{FFD92F}
\definecolor{V1A.3 133R 128K}  {HTML}{FC8D62}
\definecolor{V1A.3 133R 129N}  {HTML}{E78AC3}
\definecolor{V1A.3 133R 136K}  {HTML}{E5C494}

\newcommand{\ColorCodedBVicSecondSet}{%
  \begin{tabular}{l l}
    \cbox[V1A.3 126K]       &   V1A.3 126K        \\
    \cbox[V1A.3 133G 129N]  &   V1A.3 133G 129N   \\
    \cbox[V1A.3a]           &   V1A.3a            \\
    \cbox[V1A.3a1]          &   V1A.3a1           \\
    \cbox[V1A.3a2]          &   V1A.3a2           \\
    \cbox[V1A.3a2 122Q]     &   V1A.3a2 122Q      \\
    \cbox[V1A.3 133R]       &   V1A.3 133R        \\
    \cbox[V1A.3 133R 128K]  &   V1A.3 133R 128K   \\
    \cbox[V1A.3 133R 129N]  &   V1A.3 133R 129N   \\
    \cbox[V1A.3 133R 136K]  &   V1A.3 133R 136K   \\
  \end{tabular}
}

% \newcommand{\ColorCodedByYear}{%
% {\color{YearGrey}Grey - before 2012},
% {\color{YearOrange}Orange - 2012},
% {\color{YearBlue}Blue - 2013},
% {\color{YearMagenta}Magenta - 2014}.
% }
"""

# ----------------------------------------------------------------------

T_WhoccStatisticsTable = r"""
% ----------------------------------------------------------------------
% Table with statistics
% ----------------------------------------------------------------------
\newcommand{\WhoccStatisticsTableCellOne}[1]{#1 & & & &}
\newcommand{\WhoccStatisticsTableCellOneTotal}[1]{\color{WhoccStatisticsTableTotal}#1 & & & & }
\newcommand{\WhoccStatisticsTableCellTwo}[2]{#1 & ( & #2 & ) &}
% \newcommand{\WhoccStatisticsTableCellTwoTotal}[2]{\textbf{#1} & \textbf{(} & \textbf{#2} & \textbf{)} & }
\newcommand{\WhoccStatisticsTableCellTwoTotal}[2]{\color{WhoccStatisticsTableTotal}#1 & \color{WhoccStatisticsTableTotal}( & \color{WhoccStatisticsTableTotal}#2 & \color{WhoccStatisticsTableTotal}) & }

\newenvironment{WhoccStatisticsTable}{
  \setlength{\tabcolsep}{0pt}
  \definecolor{AlternativeRow}{HTML}{F0F0F0}
  \rowcolors{2}{AlternativeRow}{}
  \renewcommand{\arraystretch}{1.5}
  \newcommand{\ContinentHeading}[1]{\multicolumn{5}{>{\hspace{0.3em}}c<{\hspace{0.3em}}}{##1}}
  \newcommand{\ContinentHeadingTotal}[1]{\multicolumn{5}{>{\hspace{0.3em}}c<{\hspace{0.3em}}}{\color{WhoccStatisticsTableTotal}##1}}
  \newcommand{\ContinentHeadingLast}[1]{\multicolumn{5}{>{\hspace{0.3em}}c<{\hspace{0.3em}}|}{##1}}
  \newcommand{\PeriodHeading}[1]{\multicolumn{1}{|c}{##1}}
  \scriptsize
  \begin{center}
    \begin{tabular}{|>{\hspace{0.3em}}l<{\hspace{0.3em}} *{12}{>{\hspace{0.6em}}r >{\hspace{0.3em}}lrl r<{\hspace{0.5em}}}|} % >{\hspace{0.3em}\bfseries}r >{\hspace{0.3em}}lrl r<{\hspace{0.3em}} *{2}{>{\hspace{0.3em}}r >{\hspace{0.3em}}lrl r<{\hspace{0.3em}}}}
}{\end{tabular}\end{center}\par}
"""

# ----------------------------------------------------------------------

T_AntigenicMapTable = r"""
% ----------------------------------------------------------------------
% Table with antigenic maps
% ----------------------------------------------------------------------
\def \AntigenicMapTableMapSize {(\textheight-20pt) * 9 / 30} % size of an embedded antigenic map
\def \AntigenicMapTableMapSmallSize {(\textheight-20pt) * 17 / 60} % size of an embedded antigenic map

\newenvironment{AntigenicMapTable}{
  \setlength{\tabcolsep}{7pt}
  \renewcommand{\arraystretch}{3.5}
  \newcommand{\AntigenicMap}[1]{\includegraphics[width=\AntigenicMapTableMapSize,frame]{##1}}
  \newcommand{\AntigenicMapSmall}[1]{\includegraphics[width=\AntigenicMapTableMapSmallSize,frame]{##1}}
  \begin{center}
    \begin{tabular}{c c}
}{\end{tabular}\end{center}\par}

\newenvironment{AntigenicMapTableWithSep}[3]{
  \setlength{\tabcolsep}{#1}
  \renewcommand{\arraystretch}{#2}
  \newcommand{\AntigenicMap}[1]{\includegraphics[width={(\textheight-20pt) * {#3}},frame]{##1}}
  \begin{center}
    \begin{tabular}{c c}
}{\end{tabular}\end{center}\par}

\newenvironment{AntigenicMapTable3WithSep}[3]{
  \setlength{\tabcolsep}{#1}
  \renewcommand{\arraystretch}{#2}
  \newcommand{\AntigenicMap}[1]{\includegraphics[width={(\textheight-20pt) * {#3}},frame]{##1}}
  \begin{center}
    \begin{tabular}{c c c}
}{\end{tabular}\end{center}\par}
"""

# ----------------------------------------------------------------------

T_WholePagePdf = r"""
% ----------------------------------------------------------------------
% WholePagePdf
% ----------------------------------------------------------------------
\newenvironment{WholePagePdfEnv}{
   \noindent
   \begin{center}
}{\end{center}\par}
% \newcommand{\WholePagePdf}[1]{\begin{WholePagePdfEnv}\pagestyle{empty} \includepdf[pages=-,pagecommand={\thispagestyle{fancy}}]{#1}\end{WholePagePdfEnv}}
\newcommand{\WholePagePdf}[1]{\begin{WholePagePdfEnv}\pagestyle{empty} \includepdf[pages={1},noautoscale=false]{#1}\end{WholePagePdfEnv}}
\newcommand{\WholePagePdfMerge}[1]{\begin{WholePagePdfEnv}\pagestyle{empty} \includepdfmerge[]{#1}\end{WholePagePdfEnv}}
\newcommand{\WholePagePdfFit}[1]{\begin{WholePagePdfEnv}\includegraphics[page=1,scale=0.9]{#1}\end{WholePagePdfEnv}}
\newcommand{\WholePagePdfTwoToc}[3]{
  \begin{WholePagePdfEnv}
    \includepdf[pages=-,pagecommand={\pagestyle{fancy}}]{#1}
    \addcontentsline{toc}{subsection}{#2}
    \includepdf[pages=-,pagecommand={\pagestyle{fancy}}]{#3}
  \end{WholePagePdfEnv}}

"""

# ----------------------------------------------------------------------

T_SignaturePage = r"""
% ----------------------------------------------------------------------
% Signature page
% ----------------------------------------------------------------------
\newenvironment{SignaturePageEnv}{
   \noindent
   \begin{center}
}{\end{center}\par}
\newcommand{\SignaturePageFit}[1]{\begin{SignaturePageEnv}\resizebox{!}{0.98\textheight}{\includegraphics[page=1]{#1}}\end{SignaturePageEnv}}
\newcommand{\SignaturePage}[1]{\begin{SignaturePageEnv}\includegraphics[page=1]{#1}\end{SignaturePageEnv}}
\newcommand{\SignaturePageNoResacle}[1]{\includepdf[pages=-,frame=true,noautoscale=false,fitpaper=true]{#1}}
"""

# ----------------------------------------------------------------------

T_AntigenicGeneticMapSingle = r"""
% ----------------------------------------------------------------------
% Antigenic-genetic maps
% ----------------------------------------------------------------------
\def \AntigenicGeneticMapSingleMapSize {\textheight*21/30}
\newcommand{\AntigenicGeneticMapSingle}[1]{\begin{center}\includegraphics[width=\AntigenicGeneticMapSingleMapSize,frame]{#1}\end{center}}
"""

# ----------------------------------------------------------------------

T_OverviewMapSingle = r"""
% ----------------------------------------------------------------------
% Overview maps
% ----------------------------------------------------------------------
\def \OverviewMapSingleMapSize {\textheight*21/30}
\newcommand{\OverviewMapSingle}[1]{\begin{center}\includegraphics[width=\OverviewMapSingleMapSize,frame]{#1}\end{center}}
"""

# ----------------------------------------------------------------------

T_GeographicMapsTable = r"""
% ----------------------------------------------------------------------
% Table with geographic maps
% ----------------------------------------------------------------------
\def \GeographicMapsTableMapSize {\textheight * 18 / 30} % size of an embedded geographic map
\newenvironment{GeographicMapsTable}{
  \renewcommand{\arraystretch}{2.5}
  \newcommand{\GeographicMap}[1]{\includegraphics[width=\GeographicMapsTableMapSize,frame]{##1}}
  \begin{center}
    \begin{tabular}{c}
}{\end{tabular}\end{center}\par}
"""

# ----------------------------------------------------------------------

T_BlankPage = r"""
% ----------------------------------------------------------------------
% Blank page (http://tex.stackexchange.com/questions/36880/insert-a-blank-page-after-current-page)
% ----------------------------------------------------------------------
\newcommand\blankpage{%
  \newpage
  \vspace*{100pt}
  \thispagestyle{empty}%
  \newpage}
"""

# ----------------------------------------------------------------------

T_TableOfContents = r"""
% ----------------------------------------------------------------------
% ToC table of contents
% ----------------------------------------------------------------------

%% ToC http://tex.stackexchange.com/questions/163986/format-table-of-contents-with-latex
\titlecontents{section}[0cm]{\bfseries}{\\}{\\}{}
\titlecontents{subsection}[1em]{}{}{}{\titlerule*[5pc]{}\vspace{0.8ex}\thecontentspage}
\contentsmargin{120pt}

% table of content indentation
% http://tex.stackexchange.com/questions/50471/question-about-indent-lengths-in-toc
\cftsetindents{section}{0.5in}{0.5in}

%% http://tex.stackexchange.com/questions/80113/hide-section-numbers-but-keep-numbering
% \renewcommand{\thesection}{}
% \makeatletter
% \def\@seccntformat#1{\csname #1ignore\expandafter\endcsname\csname the#1\endcsname\quad}
% \let\sectionignore\@gobbletwo
% \let\latex@numberline\numberline
% \def\numberline#1{\if\relax#1\relax\else\latex@numberline{#1}\fi}
% \makeatother
% \renewcommand{\thesubsection}{\arabic{subsection}}
"""

T_TOC = r"""%no-eol%
% ----------------------------------------------------------------------
% ToC
% ----------------------------------------------------------------------

\newpage
\tableofcontents
"""
# ----------------------------------------------------------------------

T_Cover = r"""
% ----------------------------------------------------------------------
% Cover
% ----------------------------------------------------------------------

\thispagestyle{empty}

{%cover_quotation%
\vspace*{%cover_top_space%}
{
\fontsize{22}{26} \selectfont
\noindent
\textbf{Information for the WHO Consultation\\ on the Composition of Influenza Vaccines\\ for the %report_hemisphere% Hemisphere %report_year%}
\par
}

\vspace{90pt}
{
\fontsize{19}{24} \selectfont
\noindent
%teleconference%

\vspace{10pt}
\noindent
%addendum%

\vspace{50pt}
\noindent
%meeting_date%
\par
}

\vspace{%cover_after_meeting_date_space%}
{
\large
\noindent
Center for Pathogen Evolution

% \vspace{10pt}
% \noindent
% WHO Collaborating Center for Modeling, Evolution, and Control of Emerging Infectious Diseases

\vspace{10pt}
\noindent
University of Cambridge, United Kingdom
% do not remove two empty lines below


% do not remove two empty lines above!
}
}
"""

# ----------------------------------------------------------------------

T_ = r"""
"""

# ----------------------------------------------------------------------

T_ColorsBW = r"""
% ----------------------------------------------------------------------
% Continent colors for time series
% ----------------------------------------------------------------------
\definecolor{NorthAmerica}{HTML}{000000}
\definecolor{Europe}{HTML}{000000}
\definecolor{MiddleEast}{HTML}{000000}
\definecolor{NorthAmerica}{HTML}{000000}
\definecolor{SouthAmerica}{HTML}{000000}
\definecolor{CentralAmerica}{HTML}{000000}
\definecolor{Africa}{HTML}{000000}
\definecolor{Asia}{HTML}{000000}
\definecolor{Russia}{HTML}{000000}
\definecolor{AustraliaOceania}{HTML}{000000}
\definecolor{Antarctica}{HTML}{000000}
\definecolor{ChinaSouth}{HTML}{000000}
\definecolor{ChinaNorth}{HTML}{000000}
\definecolor{ChinaUnknown}{HTML}{000000}
\definecolor{Unknown}{HTML}{000000}

% ----------------------------------------------------------------------
% Point colors
% ----------------------------------------------------------------------
\definecolor{Vaccine}{HTML}{000000}
\definecolor{PreviousVaccine}{HTML}{000000}
\definecolor{Serology}{HTML}{000000}

\definecolor{YearGrey}{HTML}{000000}
\definecolor{YearOrange}{HTML}{000000}
\definecolor{YearMagenta}{HTML}{000000}
\definecolor{YearBlue}{HTML}{000000}

\definecolor{Yamagata}{HTML}{000000}
\definecolor{Victoria}{HTML}{000000}

% ----------------------------------------------------------------------
% Other colors
% ----------------------------------------------------------------------
\definecolor{WhoccStatisticsTableTotal}{HTML}{008000}
"""

# ----------------------------------------------------------------------

T_ColorsColors = r"""
% ----------------------------------------------------------------------
% Continent colors for time series
% ----------------------------------------------------------------------
\definecolor{NorthAmerica}{HTML}{000080}
\definecolor{Europe}{HTML}{00FF00}
\definecolor{MiddleEast}{HTML}{8000FF}
\definecolor{NorthAmerica}{HTML}{00008B}
\definecolor{SouthAmerica}{HTML}{40E0D0}
\definecolor{CentralAmerica}{HTML}{AAF9FF}
\definecolor{Africa}{HTML}{FF8000}
\definecolor{Asia}{HTML}{FF0000}
\definecolor{Russia}{HTML}{B03060}
\definecolor{AustraliaOceania}{HTML}{FF69B4}
\definecolor{Antarctica}{HTML}{808080}
\definecolor{ChinaSouth}{HTML}{FF0000}
\definecolor{ChinaNorth}{HTML}{6495ED}
\definecolor{ChinaUnknown}{HTML}{808080}
\definecolor{Unknown}{HTML}{808080}

% ----------------------------------------------------------------------
% Point colors
% ----------------------------------------------------------------------
\definecolor{Vaccine}{HTML}{FF0000}
\definecolor{PreviousVaccine}{HTML}{0000FF}
\definecolor{Serology}{HTML}{FFA500}

\definecolor{YearGrey}{HTML}{B0B0B0}
\definecolor{YearOrange}{HTML}{FFA500}
\definecolor{YearMagenta}{HTML}{FF00FF}
\definecolor{YearBlue}{HTML}{0000FF}

\definecolor{Yamagata}    {HTML}{FF0000}
\definecolor{Victoria}    {HTML}{0000FF}
\definecolor{Victoria2del}{HTML}{00FFFF}
\definecolor{Victoria3del}{HTML}{800080}

% ----------------------------------------------------------------------
% Other colors
% ----------------------------------------------------------------------
\definecolor{WhoccStatisticsTableTotal}{HTML}{008000}
"""

# ----------------------------------------------------------------------

T_Begin = r"""
% ****************************************************************************************************
% Document
% ----------------------------------------------------------------------

\begin{document}
\rmfamily
"""

# ----------------------------------------------------------------------

T_NoPageNumbering = r" \pagenumbering{gobble} "

T_NewPage = r"\newpage"
T_VSpace = r"\vspace{%em%em}"
T_Text_NoIndent = r"\noindent %text%"
T_Text = r"%text%"

# ----------------------------------------------------------------------

T_Section = r"\newpage \section{%title%}"
T_Subsection = r"\subsection{%title%}"

# ----------------------------------------------------------------------

T_SerumCirclesDescriptionEggCell = r"""%no-eol%
\newpage

\newgeometry{top=5em, bottom=5em, left=2.5em, right=10em}

\subsection{Serum circle description}

\vspace{1em}
% \small
\noindent
Serum circles shown in blue are for sera raised against cell passaged-viruses, in red for sera raised against egg-passaged viruses,
in orange for sera raised against reassortant viruses.


\vspace{1em}
\noindent
Strains outside a serum circle are $>$4-fold low-reactors to the homologous
titer for the serum.

\vspace{1em}
\noindent
Here we describe why serum circles have different radii. One might expect the
serum circle delimiting $>$4-fold low-reactors to have radius 2. However, this
would only be the case when the homologous titer is the same as the maximum
titer for a serum - and this is not always the case.

\vspace{1em}
\noindent
The theoretical (or "target") distance in an antigenic map from serum S to a
antigen A is $\log_2$ (max titer for serum S against any antigen) - $\log_2$
(titer for serum S against antigen A). In other words, the number of 2-folds
between the maximum titer for serum S, and the titer of serum S to antigen A.

\vspace{1em}
\noindent
Thus the theoretical distance between a serum and antigen is dependent on both
the maximum titer observed for the serum and its homologous titer.

\vspace{1em}
\noindent
If low reactors were defined as $>$4-fold from the max titer for a serum then
the theoretical radius for all serum circles would be 2 units, and this text
would not be necessary. But low reactors are defined as $>$4-fold from the
homologous titer, hence the radius is 2 units plus the number of 2-folds
between max titer and the homologous titer for a serum. Saying the same thing
mathematically the theoretical radius for a serum circle is 2 + $\log_2$ (max
titer for serum S against any antigen A) - $\log_2$ (homologous titer for
serum S).

\vspace{1em}
\noindent
In addition to the theoretical serum circle radius, we also calculate an
empirical radius. The difference is that the theoretical radius is calculated
from the target distance between sera and antigens as specified by the HI
titers, whereas the empirical radius is determined from the antigenic map and
thus the actual distances in the antigenic map between the sera and antigens.
There are some extra details about the empirical calculation but they are not
central, and are omitted here.

\vspace{1em}
\noindent
The theoretical and empirical radii are similar to each other, and are
on average only about 0.5 antigenic units different. The empirical
radius is the one shown on the antigenic maps.

\vspace{1em}
\noindent
The center of a serum circle for serum S is at the serum point in the map
for serum S.

\restoregeometry

"""

# ======================================================================
